### ISSUE TITLE
Fixes: Handling required properties in definitions generated from Prisma gen-crud-api

### ISSUE THREAD

**Issue by mastersilv3r** [godspeedsystems/godspeed-cli#82]
### Error 1
When Prisma schema has a non nullable field, the required property is not being set in the definitions, though nullable:true is being set for nullable fields.
Prisma schema 
```
model User {
  id               Int               @id @default(autoincrement())
  email            String            @unique
  password         String            ///@encrypted
  name             String?
  loanApplications LoanApplication[]
}
```
Generated definition of the user
```
User:
  type: object
  properties:
    email:
      type: string
    password:
      type: string
    name:
      type: string
      nullable: true
```
The correct output will have required set
```
User:
  type: object
  required: ['email', 'password']
  properties:
    email:
      type: string
    password:
      type: string
    name:
      type: string
      nullable: true
```
